# Generated by Django 4.0.2 on 2022-02-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user',
            new_name='username',
        ),
    ]
