# Generated by Django 4.0.2 on 2022-02-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_user_signup_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='user',
        ),
    ]
