# Generated by Django 4.0.2 on 2022-02-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_rename_username_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='uploadingdata',
        ),
        migrations.AddField(
            model_name='notes',
            name='uploadingdate',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='role',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
